image: kdeorg/ci-suse-qt512

stages:
- check
- build
- test

.clazy:
  stage: check
  script:
  - zypper -qn install clazy
  - mkdir clazy
  - cd clazy
  - cmake .. -DCMAKE_CXX_COMPILER=clazy
  - make

linux-gcc-qt512:
  stage: build
  before_script:
  - git clone https://anongit.kde.org/extra-cmake-modules
  - cd extra-cmake-modules
  - cmake . -DCMAKE_INSTALL_PREFIX=../inst
  - make install
  script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../inst
  - make
  - make install
  cache:
    paths:
    - build
